[[agents]]
  id = "myagent"

  [[agents.env_vars]]
    from_secret = "API_KEY_123"
    name = "API_KEY_123"

  [[agents.env_vars]]
    from_secret = "MINIMAX_API_KEY"
    name = "MINIMAX_API_KEY"

[hub]
  description = "zlaw hub"
  name = "main"

[nats]
